// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgCToakJi74m8EWZGPVawKBBg3GJlPccU',
    appId: '1:517180076163:web:3273044a1fae6484e66bb6',
    messagingSenderId: '517180076163',
    projectId: 'finalmad-d8a9f',
    authDomain: 'finalmad-d8a9f.firebaseapp.com',
    storageBucket: 'finalmad-d8a9f.firebasestorage.app',
    measurementId: 'G-4MDD4T63FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-kIKggQwUk6aIXnjm88NNeQtpn3G3lsI',
    appId: '1:517180076163:android:eafae69605adf5c0e66bb6',
    messagingSenderId: '517180076163',
    projectId: 'finalmad-d8a9f',
    storageBucket: 'finalmad-d8a9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhEbJAD56XXyAuP9SSZhcbeJxBjY2td8U',
    appId: '1:517180076163:ios:9542280badb6dde5e66bb6',
    messagingSenderId: '517180076163',
    projectId: 'finalmad-d8a9f',
    storageBucket: 'finalmad-d8a9f.firebasestorage.app',
    iosBundleId: 'com.example.cllaude',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhEbJAD56XXyAuP9SSZhcbeJxBjY2td8U',
    appId: '1:517180076163:ios:9542280badb6dde5e66bb6',
    messagingSenderId: '517180076163',
    projectId: 'finalmad-d8a9f',
    storageBucket: 'finalmad-d8a9f.firebasestorage.app',
    iosBundleId: 'com.example.cllaude',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgCToakJi74m8EWZGPVawKBBg3GJlPccU',
    appId: '1:517180076163:web:7b355ceddfd52a30e66bb6',
    messagingSenderId: '517180076163',
    projectId: 'finalmad-d8a9f',
    authDomain: 'finalmad-d8a9f.firebaseapp.com',
    storageBucket: 'finalmad-d8a9f.firebasestorage.app',
    measurementId: 'G-HZJRTDYH40',
  );
}
